<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['raid_add_device'] = 'Add Device';
$lang['raid_always'] = 'Always';
$lang['raid_app_description'] = 'Software RAID provides status information, reporting and administrative actions for software RAID.';
$lang['raid_app_name'] = 'Software RAID Manager';
$lang['raid_array'] = 'Array';
$lang['raid_clean'] = 'Clean';
$lang['raid_confirm_add'] = 'Please confirm you would like to add block device %s to the %s RAID array.';
$lang['raid_confirm_remove'] = 'Please confirm you would like to remove block device %s from the %s RAID array.';
$lang['raid_degraded'] = 'Degraded';
$lang['raid_device'] = 'Device';
$lang['raid_email_notification'] = 'E-mail Notification';
$lang['raid_every_30_minutes'] = 'Every 30 minutes';
$lang['raid_every_4_hours'] = 'Every 4 hours';
$lang['raid_every_minute'] = 'Every minute';
$lang['raid_frequency'] = 'Frequency';
$lang['raid_level'] = 'Level';
$lang['raid_monitor_raid'] = 'Monitor RAID';
$lang['raid_mount'] = 'Mount';
$lang['raid_no_support'] = 'No supported RAID arrays found.';
$lang['raid_not_degraded'] = 'Array is not in a degraded state.';
$lang['raid_on_failure'] = 'On failure';
$lang['raid_raid_status'] = 'RAID Status';
$lang['raid_raid_summary'] = 'RAID Summary';
$lang['raid_remove'] = 'Remove';
$lang['raid_send_mail'] = 'Send E-mail Notification';
$lang['raid_software_raid'] = 'Software RAID';
$lang['raid_sync_pending'] = 'Sync pending';
$lang['raid_sync_scheduled'] = 'Sync scheduled';
$lang['raid_syncing'] = 'Sync in progress';
$lang['raid_test_email'] = 'Send Test E-mail';
$lang['raid_test_sent_to:'] = 'Success.  E-mail notification has been sent to:';
$lang['raid_type'] = 'Type';
$lang['raid_vendor'] = 'Vendor';
