#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * RAID Notification.
 *
 * @category   apps
 * @package    raid
 * @subpackage scripts
 * @author     ClearFoundation <developer@clearfoundation.com>
 * @copyright  2008-2011 ClearFoundation
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/raid/
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// N A M E S P A C E
///////////////////////////////////////////////////////////////////////////////

namespace clearos\apps\raid;

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('raid');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\raid\Raid as Raid;

clearos_load_library('raid/Raid');

// Exceptions
//-----------

use \Exception as Exception;

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

// Command line options
//--------------------------------------------------------------------

$short_options  = '';
$short_options .= 'f';  // Force display and alert status
$short_options .= 's';  // Force send of email

$options = getopt($short_options);

$force = isset($options['f']) ? TRUE : FALSE;
$send = isset($options['s']) ? TRUE : FALSE;

// Command line options
//---------------------

$raid = new Raid();

try {
    $changes = $raid->check_status_change($force, $send);
    if (is_array($changes)) {
        foreach ($changes as $line)
            echo $line . "\n";
    } else {
        echo "No changes since last check.\n";
    } 
} catch (Exception $e) {
    echo clearos_exception_message($e) . "\n";
    clearos_log('raid', clearos_exception_message($e));
}

// vim: syntax=php ts=4
