<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['raid_add_device'] = 'Dodaj urządzenie';
$lang['raid_always'] = 'Zawsze';
$lang['raid_app_description'] = 'RAID Programowy dostarcza informacji o stanie, operacje raportowe i administracyjne dla programowego RAID.';
$lang['raid_app_name'] = 'Manager programowego RAID';
$lang['raid_array'] = 'Macierz';
$lang['raid_clean'] = 'Wyczyść';
$lang['raid_confirm_add'] = 'Proszę potwierdzić chęć dodania urządzenia blokowego %s do %s macierzy RAID.';
$lang['raid_confirm_remove'] = 'Proszę potwierdzić chęć usunięcia urządzenia blokowego %s z %s macierzy RAID.';
$lang['raid_degraded'] = 'Zdegradowany';
$lang['raid_device'] = 'Urządzenie';
$lang['raid_email_notification'] = 'Powiadomienie e-mail';
$lang['raid_every_30_minutes'] = 'Co 30 minut';
$lang['raid_every_4_hours'] = 'Co 4 godziny';
$lang['raid_every_minute'] = 'Co minutę';
$lang['raid_frequency'] = 'Częstotliwość';
$lang['raid_level'] = 'Poziom';
$lang['raid_monitor_raid'] = 'Monitoring RAID';
$lang['raid_mount'] = 'Zamontuj';
$lang['raid_no_support'] = 'Nie znaleziono obsługiwanych macierzy RAID.';
$lang['raid_not_degraded'] = 'Macierz nie jest zdegradowana.';
$lang['raid_on_failure'] = 'Podczas awarii';
$lang['raid_raid_status'] = 'Stan RAID';
$lang['raid_raid_summary'] = 'Podsumowanie RAID';
$lang['raid_remove'] = 'Usuń';
$lang['raid_send_mail'] = 'Wyślij powiadomienie e-mail';
$lang['raid_software_raid'] = 'Programowy RAID';
$lang['raid_sync_pending'] = 'Oczekująca synchronizacja';
$lang['raid_sync_scheduled'] = 'Zaplanowana synchronizacja';
$lang['raid_syncing'] = 'Synchronizacja w toku';
$lang['raid_test_email'] = 'Wyślij testowy e-mail';
$lang['raid_test_sent_to:'] = 'Sukces.  Powiadomienie e-mail zostało wysłane do:';
$lang['raid_type'] = 'Typ';
$lang['raid_vendor'] = 'Producent';
